export const vessels = [
  {
    id: 1,
    vesselName: "EBL-2869",
    vesselType: "Barge",
    branch: "Houston",
    status: "Active",
  },
  {
    id: 2,
    vesselName: "EBL-2900",
    vesselType: "Barge",
    branch: "New York",
    status: "Inactive",
  },
  {
    id: 3,
    vesselName: "EBL-2971 & 2972",
    vesselType: "Tow",
    branch: "Texas",
    status: "Active",
  },

  // --- 100 more rows generated ---
  {
    id: 4,
    vesselName: "EBL-3001",
    vesselType: "Tow",
    branch: "Houston",
    status: "Active",
  },
  {
    id: 5,
    vesselName: "EBL-3002",
    vesselType: "Barge",
    branch: "Louisiana",
    status: "Inactive",
  },
  {
    id: 6,
    vesselName: "EBL-3003",
    vesselType: "Tow",
    branch: "Florida",
    status: "Active",
  },
  {
    id: 7,
    vesselName: "EBL-3004",
    vesselType: "Barge",
    branch: "Texas",
    status: "Active",
  },
  {
    id: 8,
    vesselName: "EBL-3005",
    vesselType: "Tow",
    branch: "Houston",
    status: "Inactive",
  },
  {
    id: 9,
    vesselName: "EBL-3006",
    vesselType: "Barge",
    branch: "Louisiana",
    status: "Active",
  },
  {
    id: 10,
    vesselName: "EBL-3007",
    vesselType: "Tow",
    branch: "New York",
    status: "Inactive",
  },
  {
    id: 11,
    vesselName: "EBL-3008",
    vesselType: "Barge",
    branch: "California",
    status: "Active",
  },
  {
    id: 12,
    vesselName: "EBL-3009",
    vesselType: "Tow",
    branch: "Alabama",
    status: "Active",
  },
  {
    id: 13,
    vesselName: "EBL-3010",
    vesselType: "Barge",
    branch: "Florida",
    status: "Inactive",
  },

  {
    id: 14,
    vesselName: "EBL-3011",
    vesselType: "Tow",
    branch: "Texas",
    status: "Active",
  },
  {
    id: 15,
    vesselName: "EBL-3012",
    vesselType: "Barge",
    branch: "Georgia",
    status: "Inactive",
  },
  {
    id: 16,
    vesselName: "EBL-3013",
    vesselType: "Tow",
    branch: "Houston",
    status: "Active",
  },
  {
    id: 17,
    vesselName: "EBL-3014",
    vesselType: "Barge",
    branch: "New York",
    status: "Active",
  },
  {
    id: 18,
    vesselName: "EBL-3015",
    vesselType: "Tow",
    branch: "Florida",
    status: "Inactive",
  },
  {
    id: 19,
    vesselName: "EBL-3016",
    vesselType: "Barge",
    branch: "California",
    status: "Active",
  },
  {
    id: 20,
    vesselName: "EBL-3017",
    vesselType: "Tow",
    branch: "Georgia",
    status: "Active",
  },

  {
    id: 21,
    vesselName: "EBL-3018",
    vesselType: "Barge",
    branch: "Houston",
    status: "Inactive",
  },
  {
    id: 22,
    vesselName: "EBL-3019",
    vesselType: "Tow",
    branch: "Texas",
    status: "Active",
  },
  {
    id: 23,
    vesselName: "EBL-3020",
    vesselType: "Barge",
    branch: "Louisiana",
    status: "Inactive",
  },
  {
    id: 24,
    vesselName: "EBL-3021",
    vesselType: "Tow",
    branch: "Alabama",
    status: "Active",
  },
  {
    id: 25,
    vesselName: "EBL-3022",
    vesselType: "Barge",
    branch: "Georgia",
    status: "Active",
  },
  {
    id: 26,
    vesselName: "EBL-3023",
    vesselType: "Tow",
    branch: "New York",
    status: "Inactive",
  },
  {
    id: 27,
    vesselName: "EBL-3024",
    vesselType: "Barge",
    branch: "Texas",
    status: "Active",
  },
  {
    id: 28,
    vesselName: "EBL-3025",
    vesselType: "Tow",
    branch: "Florida",
    status: "Active",
  },
  {
    id: 29,
    vesselName: "EBL-3026",
    vesselType: "Barge",
    branch: "California",
    status: "Inactive",
  },
  {
    id: 30,
    vesselName: "EBL-3027",
    vesselType: "Tow",
    branch: "Houston",
    status: "Active",
  },

  {
    id: 31,
    vesselName: "EBL-3028",
    vesselType: "Barge",
    branch: "Louisiana",
    status: "Active",
  },
  {
    id: 32,
    vesselName: "EBL-3029",
    vesselType: "Tow",
    branch: "Texas",
    status: "Inactive",
  },
  {
    id: 33,
    vesselName: "EBL-3030",
    vesselType: "Barge",
    branch: "California",
    status: "Active",
  },
  {
    id: 34,
    vesselName: "EBL-3031",
    vesselType: "Tow",
    branch: "Georgia",
    status: "Active",
  },
  {
    id: 35,
    vesselName: "EBL-3032",
    vesselType: "Barge",
    branch: "Florida",
    status: "Inactive",
  },
  {
    id: 36,
    vesselName: "EBL-3033",
    vesselType: "Tow",
    branch: "Houston",
    status: "Active",
  },
  {
    id: 37,
    vesselName: "EBL-3034",
    vesselType: "Barge",
    branch: "Alabama",
    status: "Active",
  },
  {
    id: 38,
    vesselName: "EBL-3035",
    vesselType: "Tow",
    branch: "New York",
    status: "Inactive",
  },
  {
    id: 39,
    vesselName: "EBL-3036",
    vesselType: "Barge",
    branch: "Texas",
    status: "Active",
  },
  {
    id: 40,
    vesselName: "EBL-3037",
    vesselType: "Tow",
    branch: "Georgia",
    status: "Active",
  },

  ...Array.from({ length: 60 }).map((_, i) => ({
    id: 41 + i,
    vesselName: `EBL-${3040 + i}`,
    vesselType: ["Barge", "Tow"][Math.floor(Math.random() * 2)],
    branch: ["Houston", "Texas", "Florida", "Louisiana", "New York", "Georgia"][
      Math.floor(Math.random() * 6)
    ],
    status: ["Active", "Inactive"][Math.floor(Math.random() * 2)],
  })),
];
