export const vessel = {
  vesselName: "EBL-2869",
  vesselType: "Barge",
  imo: "1234567",
  active: true,
  branch: "Houston",
  vetUnits: "USG",
  draftUnit: "FT",
  gaugeUnit: "IN",
  volumeUnit: "BBL",
  vesselCapacity: "20000",
  compartments: "12",
  sandPipe: "Yes",
  lengthOverall: "125 FT",

  additional: {
    beam: "12 FT",
    draught: "8 FT",
    vesselLine: "2.5",
    vesselConnectionType: "Flange",
    ballast: "Yes",
    manifoldLocation: "Deck",
    lop: "22",
    flyingFlag: "US",
    buildYear: "2008",
    lastSampling: "01-Jan-2024",
    lastDryDock: "20-Feb-2023",
    formerName: "Old Spirit",
    bargeCompany: "Marine LLC",
    vesselPhone: "+1 202-555-9241",
    vesselEmail: "ship@marine.com",
    vesselWebsite: "https://marine.com",
    grossRegTons: "190000",
    netRegTons: "150000",
    vesselClass: "A-Class",
    oceanGoing: "Yes",
  },

  owners: [
    {
      id: 1,
      name: "Vessel Management",
      eff: "01-Aug-2023",
      exp: "30-Jul-2026",
    },
    { id: 2, name: "Victory Spirit", eff: "01-Aug-2022", exp: "31-Dec-2024" },
  ],

  notes: "Routine maintenance scheduled for next month.",
};
